service: DiscordSlashBot

app: trapa-security-interview
org: shirinmi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:ap-southeast-1:347819602869:secret:prod/TRAPASecurityInterview/discord-HeDAlO"
        - Effect: "Allow"
          Action:
            - "scheduler:CreateSchedule"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource: "arn:aws:iam::347819602869:role/cronScheduler"

functions:
  discord:
    handler: src/handler.discord
  register:
    handler: src/handler.register
  cron:
    handler: src/cronHandler.cron
    url: false

plugins:
  - serverless-provisioned-concurrency-autoscaling